apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logic
  name: logic
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8081
  - name: "1337"
    port: 1337
    protocol: TCP
    targetPort: 8080
  selector:
    service: logic
status:
  loadBalancer: {}
