apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: pcs
  name: pcs
spec:
  type: NodePort
  ports:
  - name: "9090"
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    service: pcs
status:
  loadBalancer: {}
