apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: portal
  name: portal
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: portal
status:
  loadBalancer: {}
